/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic;

import ilog.concert.IloException;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;

import model.Graph;
import model.GraphStochastique;
import model.Solution;
import controller.LinearProgram;
import controller.Parser;
import controller.ps.ProblemeStochastique;

/**
 *
 * @author Younes
 */
public class Luncher extends javax.swing.JFrame {

	/**
	 * Creates new form Luncher
	 */
	String url = "";
	public static File file = null;

	public Luncher() {
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel3 = new javax.swing.JPanel();
		jTabbedPane2 = new javax.swing.JTabbedPane();
		jPanel4 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jCheckBox1 = new javax.swing.JCheckBox();
		jSpinner1 = new javax.swing.JSpinner();
		jSpinner2 = new javax.swing.JSpinner();
		jButton2 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jButton3 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		jLabel8 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("TSP Solver");
		setResizable(false);

		jPanel3.setBackground(new java.awt.Color(222, 246, 245));

		jPanel4.setBackground(new java.awt.Color(222, 246, 245));

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
		jLabel2.setText("Paramètres");

		jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel3.setText("Nombre de scénarios");

		jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel4.setText("Affichage d'arrêtes");

		jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		jLabel5.setText("Pourcentage d'arrêtes aléatoires");

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
		jLabel6.setText("Valeurs");

		jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer
				.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

		jSpinner2.setModel(new javax.swing.SpinnerNumberModel(Integer
				.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

		jButton2.setText("Résoudre Stochastique");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(33, 33, 33)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addGap(306,
																				306,
																				306))
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addGroup(
																				jPanel4Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								144,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(265,
																								265,
																								265))
																		.addComponent(
																				jLabel5,
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(
																				jLabel3,
																				javax.swing.GroupLayout.Alignment.LEADING)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												142, Short.MAX_VALUE)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(40,
																				40,
																				40)
																		.addComponent(
																				jCheckBox1))
														.addComponent(jLabel6)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(11,
																				11,
																				11)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jSpinner1)
																						.addComponent(
																								jSpinner2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								50,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addGap(99, 99, 99))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(jButton2)
										.addContainerGap()));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(74, 74, 74)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(jLabel6))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jSpinner1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																jSpinner2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jCheckBox1))
										.addGap(96, 96, 96)
										.addComponent(jButton2)
										.addContainerGap(58, Short.MAX_VALUE)));

		jTabbedPane2.addTab("Stochastique", jPanel4);

		jPanel2.setBackground(new java.awt.Color(222, 246, 245));

		jButton3.setText("Résoudre");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addGap(322, 322, 322)
						.addComponent(jButton3)
						.addContainerGap(343, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel2Layout.createSequentialGroup().addGap(58, 58, 58)
						.addComponent(jButton3)
						.addContainerGap(298, Short.MAX_VALUE)));

		jTabbedPane2.addTab("PNE", jPanel2);

		jLabel1.setText("Chemin du fichier XML");

		jButton1.setText("Parcourir");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jTabbedPane2)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				542,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton1)
																		.addGap(12,
																				12,
																				12)))
										.addContainerGap()));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(49, 49, 49)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												47, Short.MAX_VALUE)
										.addComponent(
												jTabbedPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												407,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(48, 48, 48)));

		jTabbedPane1.addTab("Accueil", jPanel3);

		jPanel1.setBackground(new java.awt.Color(222, 246, 245));

		jLabel7.setText("Graphe");

		jPanel5.setBackground(new java.awt.Color(255, 255, 255));

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 298,
				Short.MAX_VALUE));

		jLabel8.setText("Console");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jPanel5,
								javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																749,
																Short.MAX_VALUE)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel8))
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel7)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jPanel5,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel8)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												214, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Résultat", jPanel1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jTabbedPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 774,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap()
						.addComponent(jTabbedPane1).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		JFileChooser choice = new JFileChooser();
		if (file != null) {
			choice.setCurrentDirectory(file);
		}
		File workingDirectory = new File(System.getProperty("user.dir"));
		choice.setCurrentDirectory(workingDirectory);
		int tempo = choice.showOpenDialog(jPanel1);
		if (tempo == JFileChooser.APPROVE_OPTION) {
			jTextField1.setText(choice.getSelectedFile().getAbsolutePath());
			url = choice.getSelectedFile().getAbsolutePath();
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
		try {
			pne();
		} catch (IloException ex) {
			Logger.getLogger(Luncher.class.getName()).log(Level.SEVERE, null,
					ex);
		} catch (IOException ex) {
			Logger.getLogger(Luncher.class.getName()).log(Level.SEVERE, null,
					ex);
		}
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		try {
			stochastique();
		} catch (IloException ex) {
			Logger.getLogger(Luncher.class.getName()).log(Level.SEVERE, null,
					ex);
		} catch (IOException ex) {
			Logger.getLogger(Luncher.class.getName()).log(Level.SEVERE, null,
					ex);
		}
	}// GEN-LAST:event_jButton2ActionPerformed

	private void pne() throws IloException, IOException {
		JGraphAdapter gApplet = new JGraphAdapter();
		Graph g = gApplet.init(url);
		Parser p = new Parser(url);
		Graph graph_parsed = p.parse();
		LinearProgram lp = new LinearProgram(graph_parsed);
		jPanel5.add(gApplet);
		console(lp);
		jTabbedPane1.setSelectedIndex(1);
	}

	private void stochastique() throws IloException, IOException {
		Integer nbrScenario = Integer.parseInt(jSpinner1.getValue().toString());
		Integer pourcentageAleatoire = Integer.parseInt(jSpinner2.getValue().toString());
		System.out.println("nbrScenario "+ nbrScenario);
		System.out.println("pourcentageAleatoire "+  pourcentageAleatoire);
		if ((Integer.parseInt(jSpinner1.getValue().toString()) >= 10)
				&& (Integer.parseInt(jSpinner1.getValue().toString()) >= 10)) {
			JGraphAdapter gApplet = new JGraphAdapter();
			Graph g = gApplet.init(url);
			Parser p = new Parser(url);
			System.out.println("Chargement du fichier XML...");
			GraphStochastique graph_parsed = new GraphStochastique(p.parse());
			System.out.println("Fin de chargement du fichier");
			System.out.println("Nombre de ville = " + g.getNbrVertex());
			ProblemeStochastique ps = new ProblemeStochastique(graph_parsed, 5);

			jPanel5.add(gApplet);
			console(ps,nbrScenario,pourcentageAleatoire);
			jTabbedPane1.setSelectedIndex(1);
		}
	}

	private void console(ProblemeStochastique ps,int nbrScenario,int pourcentageAleatoire) throws IOException {
		// graph_parsed.printGraph();

		// Graph graph_solution = ps.solve();
		System.out.println("Graph Initial");
		System.out.println("================ DEB ================");
		ps.getGraphEntree().printGraph();
		System.out.println("================ FIN =================");
		long begin = System.currentTimeMillis();
		Solution resultat = ps.solve(pourcentageAleatoire, nbrScenario, 5, 5);
		long end = System.currentTimeMillis();
		float millis = (float) (end - begin) / 1000;

		this.jTextArea1.removeAll();
		this.jTextArea1.append("Le chemin de la solution est : \n");
		this.jTextArea1.append(resultat.getArcs().toString() + "\n");
		this.jTextArea1.append("La Soltion Optimal est : "
				+ resultat.getTotalCost(ps.getGraphEntree()) + "\n");
		this.jTextArea1.append("Temps d'execution = " + millis + "\n");
	}

	private void console(LinearProgram lp) throws IOException {
		long begin = System.currentTimeMillis();
		Graph g = lp.solve();
		long end = System.currentTimeMillis();
		float millis = (float) (end - begin) / 1000;

		this.jTextArea1.removeAll();
		this.jTextArea1.append("Le chemin de la solution est : \n");
		for (int i = 0; i < lp.nbrVar; i++) {
			for (int j = 0; j < lp.nbrVar; j++) {
				if (lp.solution_Final[i][j] == 1) {
					// System.out.println("X[" + i + "," + j + "]");
					this.jTextArea1.append("X[" + i + "," + j + "]" + "\n");
				}
			}

		}
		this.jTextArea1.append("La Soltion Optimal est : " + lp.optimalSol
				+ "\n");
		this.jTextArea1.append("Temps d'execution = " + millis + "\n");
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Luncher.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Luncher.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Luncher.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Luncher.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Luncher().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSpinner jSpinner1;
	private javax.swing.JSpinner jSpinner2;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTabbedPane jTabbedPane2;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables
}
