/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphic;

import ilog.concert.IloException;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import model.Graph;
import controller.LinearProgram;
import controller.Parser;

/**
 * 
 * @author Younes
 */
public class test extends javax.swing.JFrame {

	/**
	 * Creates new form test
	 */
	String xmlFile = "";

	public test(String url) {

		// file = new File(jTextField1.getText()).getParentFile();
		xmlFile = url;
		// JGraphXAdapterDemo gApplet = new JGraphXAdapterDemo();
		JGraphAdapterDemo gApplet = new JGraphAdapterDemo();
		gApplet.init(xmlFile);

		this.add(gApplet);
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);

		jScrollPane1.setViewportView(jTextArea1);

		jButton1.setText("Resolve");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0,
				Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 376,
				Short.MAX_VALUE));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														758, Short.MAX_VALUE)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(0,
																		0,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton1)))
								.addContainerGap())
				.addComponent(jPanel1,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										55, Short.MAX_VALUE)
								.addComponent(jButton1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										137,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

		try {

			Parser p = new Parser(this.xmlFile);
			Graph graph_parsed = p.parse();
			
			LinearProgram lp = new LinearProgram(graph_parsed);
			



			
			try {
				long begin = System.currentTimeMillis();
				Graph graph_solved = lp.solve();
				long end = System.currentTimeMillis();
				float millis = (float) (end - begin) / 1000;

				this.jTextArea1.removeAll();
				this.jTextArea1.append("Le chemin de la solution est : \n");
				for (int i = 0; i < lp.nbrVar; i++) {
				for (int j = 0; j < lp.nbrVar; j++) {
					if (lp.solution_Final[i][j] == 1) {
						// System.out.println("X[" + i + "," + j + "]");
						this.jTextArea1.append("X[" + i + "," + j + "]"+"\n");
					}
				}
			}
				this.jTextArea1.append("La Soltion Optimal est : " + lp.optimalSol+"\n");
				this.jTextArea1.append("Temps d'execution = " + millis+"\n");
				

			} catch (IOException ex) {
				Logger.getLogger(test.class.getName()).log(Level.SEVERE, null,
						ex);
			}
		} catch (IloException ex) {
			Logger.getLogger(test.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	public javax.swing.JTextArea jTextArea1;
	// End of variables declaration//GEN-END:variables
}
